### PR TITLE
Add Ingress dummy paths to block access to the `/swagger`, `/metrics`, and `/api/health` endpoints by default

### PR DESCRIPTION
**Pull request by TheoBrigitte**
Towards: https://github.com/giantswarm/giantswarm/issues/31448

This PR adds a deny rule to the nginx configuration for the /swagger endpoint. This is to prevent Swagger queryConfig malicious usage, see https://github.com/swagger-api/swagger-ui/issues/4332.

This makes our values file drift from upstream, and make future upgrade more "complex" but that change is aimed at improving default security settings.

### CODE REVIEW

**Comment by QuentinBisson** [comment]
BTW @Gacko is configuration snippet not going away?

**Comment by hervenicol** [comment]
> This makes our values file drift from upstream, and make future upgrade more "complex"

I never noticed we had such a big custom `values.yaml` :astonished:
It probably already drifted since it's been imported here! :grimacing:

**Review by hervenicol — APPROVED** [review]

**Comment by TheoBrigitte** [comment]
> BTW @Gacko is configuration snippet not going away?

Sounds like yes

```
    Reason: Upgrade "grafana" failed: cannot patch "grafana" with kind Ingress: admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: nginx.ingress.kubernetes.io/configuration-snippet annotation cannot be used. Snippet directives are disabled by the Ingress administrator
```

**Comment by TheoBrigitte** [comment]
Switched to using dummy ingress additional paths, which are more portable and works well. The "dummy" path return 503 errors.

image

Here is an example of a final Ingress resources after install this app with ingress enabled.

image

**Review by QuentinBisson — APPROVED** [review]

**Pull request merged**
